name: Import

on:
  create:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Import
    runs-on: ubuntu-latest
    steps:
    - name: Push the changes
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git clone https://github.com/Wikia/app.git --depth=1
        cd app
        wget https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
        python3 git-filter-repo --force --path extensions/wikia/ArticleComments/ --source extensions/wikia/ArticleComments/ --target ./
        rm git-filter-repo
        git add .
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git commit -m "Import from https://github.com/Wikia/app/tree/dev/extensions/wikia/ArticleComments" || echo "No changes to commit"
        git pull origin dev --rebase
        git push -u origin dev
